import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '@/contexts/AuthContext';
import { useRouter } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';

interface CarbonData {
  daily: number;
  weekly: number;
  monthly: number;
  yearly: number;
}

const CarbonReportScreen = () => {
  const { user } = useAuth();
  const router = useRouter();
  const [carbonData, setCarbonData] = useState<CarbonData>({
    daily: 0,
    weekly: 0,
    monthly: 0,
    yearly: 0,
  });

  useEffect(() => {
    // Simulate fetching carbon footprint data
    // In a real app, this would come from your API
    setCarbonData({
      daily: 8.2,
      weekly: 57.4,
      monthly: 248.0,
      yearly: 2976.0,
    });
  }, []);

  const goBack = () => {
    router.back();
  };

  const generatePDFContent = () => {
    return `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            .header { text-align: center; color: #4CAF50; margin-bottom: 30px; }
            .overview { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
            .stat-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }
            .stat-card { background: white; padding: 15px; border-radius: 8px; text-align: center; border: 1px solid #ddd; }
            .breakdown { margin: 20px 0; }
            .breakdown-item { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #eee; }
            .goals { background: #e8f5e8; padding: 20px; border-radius: 8px; margin-top: 20px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>🌍 Carbon Footprint Report</h1>
            <p>Generated on ${new Date().toLocaleDateString()}</p>
            <p>User: ${user?.name || 'EcoTrack User'}</p>
          </div>
          
          <div class="overview">
            <h2>Current Carbon Impact</h2>
            <p><strong>Today:</strong> ${carbonData.daily} kg CO₂</p>
            <p><strong>Status:</strong> ${carbonData.daily > (user?.carbonProfile?.goals?.daily || 7.1) ? 'Above target ⚠️' : 'Within target ✅'}</p>
          </div>

          <div class="stat-grid">
            <div class="stat-card">
              <h3>${carbonData.weekly} kg</h3>
              <p>Weekly CO₂</p>
            </div>
            <div class="stat-card">
              <h3>${carbonData.monthly} kg</h3>
              <p>Monthly CO₂</p>
            </div>
            <div class="stat-card">
              <h3>${carbonData.yearly} kg</h3>
              <p>Yearly CO₂</p>
            </div>
          </div>

          <div class="breakdown">
            <h2>Emissions Breakdown</h2>
            <div class="breakdown-item">
              <span>🚗 Transportation</span>
              <span>3.2 kg CO₂</span>
            </div>
            <div class="breakdown-item">
              <span>🏠 Energy Usage</span>
              <span>2.8 kg CO₂</span>
            </div>
            <div class="breakdown-item">
              <span>🍽️ Food</span>
              <span>1.5 kg CO₂</span>
            </div>
            <div class="breakdown-item">
              <span>♻️ Waste</span>
              <span>0.7 kg CO₂</span>
            </div>
          </div>

          <div class="goals">
            <h2>Your Goals</h2>
            <p><strong>Daily Goal:</strong> ${user?.carbonProfile?.goals?.daily?.toFixed(1) || '7.1'} kg CO₂</p>
            <p><strong>Weekly Goal:</strong> ${user?.carbonProfile?.goals?.weekly?.toFixed(1) || '49.7'} kg CO₂</p>
            <p><strong>Monthly Goal:</strong> ${user?.carbonProfile?.goals?.monthly?.toFixed(1) || '213.0'} kg CO₂</p>
          </div>

          <div style="margin-top: 30px; text-align: center; color: #666;">
            <p>Generated by EcoTrack - Making the world greener, one habit at a time 🌱</p>
          </div>
        </body>
      </html>
    `;
  };

  const exportToPDF = async () => {
    try {
      const htmlContent = generatePDFContent();
      const { uri } = await Print.printToFileAsync({
        html: htmlContent,
        base64: false
      });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Share Carbon Footprint Report',
          UTI: 'com.adobe.pdf'
        });
      } else {
        Alert.alert('Success', 'PDF report generated successfully!');
      }
    } catch (error) {
      console.error('Error generating PDF:', error);
      Alert.alert('Error', 'Failed to generate PDF report');
    }
  };

  const exportToCSV = async () => {
    try {
      const csvContent = `Carbon Footprint Report,Generated on ${new Date().toLocaleDateString()}
User,${user?.name || 'EcoTrack User'}
Email,${user?.email || 'N/A'}

Period,CO2 Emissions (kg)
Daily,${carbonData.daily}
Weekly,${carbonData.weekly}
Monthly,${carbonData.monthly}
Yearly,${carbonData.yearly}

Breakdown Category,CO2 Emissions (kg)
Transportation,3.2
Energy Usage,2.8
Food,1.5
Waste,0.7

Goals,Target (kg CO2)
Daily Goal,${user?.carbonProfile?.goals?.daily?.toFixed(1) || '7.1'}
Weekly Goal,${user?.carbonProfile?.goals?.weekly?.toFixed(1) || '49.7'}
Monthly Goal,${user?.carbonProfile?.goals?.monthly?.toFixed(1) || '213.0'}`;

      const fileUri = FileSystem.documentDirectory + `carbon-report-${Date.now()}.csv`;
      await FileSystem.writeAsStringAsync(fileUri, csvContent, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/csv',
          dialogTitle: 'Share Carbon Footprint Report',
        });
      } else {
        Alert.alert('Success', 'CSV report generated successfully!');
      }
    } catch (error) {
      console.error('Error generating CSV:', error);
      Alert.alert('Error', 'Failed to generate CSV report');
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={goBack} style={styles.backButton}>
          <Text style={styles.backText}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Carbon Report</Text>
        <View style={styles.exportButtons}>
          <TouchableOpacity onPress={exportToCSV} style={styles.exportButton}>
            <Text style={styles.exportText}>CSV</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={exportToPDF} style={styles.exportButton}>
            <Text style={styles.exportText}>PDF</Text>
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView style={styles.scrollView}>
        <View style={styles.content}>
          {/* Overview Card */}
          <View style={styles.overviewCard}>
            <Text style={styles.cardTitle}>Your Carbon Impact</Text>
            <Text style={styles.subtitle}>Current Status</Text>
            
            <View style={styles.mainStat}>
              <Text style={styles.mainValue}>{carbonData.daily} kg</Text>
              <Text style={styles.mainLabel}>CO₂ Today</Text>
            </View>

            <View style={styles.goalComparison}>
              <Text style={styles.goalText}>
                Daily Goal: {user?.carbonProfile?.goals?.daily?.toFixed(1) || '7.1'} kg CO₂
              </Text>
              <Text style={styles.goalStatus}>
                {carbonData.daily > (user?.carbonProfile?.goals?.daily || 7.1) 
                  ? '⚠️ Above target' 
                  : '✅ Within target'}
              </Text>
            </View>
          </View>

          {/* Time Period Stats */}
          <View style={styles.statsGrid}>
            <View style={styles.statCard}>
              <Text style={styles.statValue}>{carbonData.weekly}</Text>
              <Text style={styles.statLabel}>Weekly (kg CO₂)</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statValue}>{carbonData.monthly}</Text>
              <Text style={styles.statLabel}>Monthly (kg CO₂)</Text>
            </View>
            <View style={styles.statCard}>
              <Text style={styles.statValue}>{carbonData.yearly}</Text>
              <Text style={styles.statLabel}>Yearly (kg CO₂)</Text>
            </View>
          </View>

          {/* Breakdown */}
          <View style={styles.breakdownCard}>
            <Text style={styles.cardTitle}>Emissions Breakdown</Text>
            
            <View style={styles.breakdownItem}>
              <Text style={styles.breakdownIcon}>🚗</Text>
              <Text style={styles.breakdownText}>Transportation</Text>
              <Text style={styles.breakdownValue}>3.2 kg</Text>
            </View>
            
            <View style={styles.breakdownItem}>
              <Text style={styles.breakdownIcon}>🏠</Text>
              <Text style={styles.breakdownText}>Energy Usage</Text>
              <Text style={styles.breakdownValue}>2.8 kg</Text>
            </View>
            
            <View style={styles.breakdownItem}>
              <Text style={styles.breakdownIcon}>🍽️</Text>
              <Text style={styles.breakdownText}>Food & Dining</Text>
              <Text style={styles.breakdownValue}>1.8 kg</Text>
            </View>
            
            <View style={styles.breakdownItem}>
              <Text style={styles.breakdownIcon}>🛍️</Text>
              <Text style={styles.breakdownText}>Shopping</Text>
              <Text style={styles.breakdownValue}>0.4 kg</Text>
            </View>
          </View>

          {/* Recommendations */}
          <View style={styles.recommendationsCard}>
            <Text style={styles.cardTitle}>Recommendations</Text>
            
            <View style={styles.recommendation}>
              <Text style={styles.recommendationIcon}>🚲</Text>
              <View style={styles.recommendationContent}>
                <Text style={styles.recommendationTitle}>Try cycling to work</Text>
                <Text style={styles.recommendationDesc}>Could save 2.1 kg CO₂ per day</Text>
              </View>
            </View>
            
            <View style={styles.recommendation}>
              <Text style={styles.recommendationIcon}>💡</Text>
              <View style={styles.recommendationContent}>
                <Text style={styles.recommendationTitle}>Switch to LED bulbs</Text>
                <Text style={styles.recommendationDesc}>Reduce energy consumption by 80%</Text>
              </View>
            </View>
            
            <View style={styles.recommendation}>
              <Text style={styles.recommendationIcon}>🥗</Text>
              <View style={styles.recommendationContent}>
                <Text style={styles.recommendationTitle}>Eat more plant-based meals</Text>
                <Text style={styles.recommendationDesc}>Lower food-related emissions</Text>
              </View>
            </View>
          </View>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  backButton: {
    marginRight: 15,
  },
  backText: {
    fontSize: 16,
    color: '#007AFF',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333333',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  overviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 15,
  },
  mainStat: {
    alignItems: 'center',
    marginBottom: 15,
  },
  mainValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FF6B6B',
  },
  mainLabel: {
    fontSize: 16,
    color: '#666666',
  },
  goalComparison: {
    backgroundColor: '#F8F9FA',
    padding: 15,
    borderRadius: 8,
  },
  goalText: {
    fontSize: 14,
    color: '#333333',
    marginBottom: 5,
  },
  goalStatus: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  statCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 15,
    flex: 1,
    marginHorizontal: 5,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 5,
  },
  statLabel: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
  },
  breakdownCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  breakdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  breakdownIcon: {
    fontSize: 24,
    marginRight: 15,
    width: 30,
  },
  breakdownText: {
    flex: 1,
    fontSize: 16,
    color: '#333333',
  },
  breakdownValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FF6B6B',
  },
  recommendationsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  recommendation: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  recommendationIcon: {
    fontSize: 24,
    marginRight: 15,
    width: 30,
  },
  recommendationContent: {
    flex: 1,
  },
  recommendationTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 2,
  },
  recommendationDesc: {
    fontSize: 14,
    color: '#666666',
  },
  exportButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  exportButton: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  exportText: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
});

export default CarbonReportScreen;